/**
    Copyright 2020 Anton "Vuvk" Shcherbatykh

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/
package com.vuvk.voxelspace.forms;

import com.vuvk.voxelspace.Camera;
import com.vuvk.voxelspace.Global;
import java.awt.Color;
import java.util.HashMap;

/**
 *
 * @author Anton "Vuvk" Shcherbatykh
 */
public class FormSettings extends javax.swing.JFrame {
    
    private final static HashMap<String,String> MAPS = new HashMap<>();
    static {
        MAPS.put("C1W.png",  "D1.png");
        MAPS.put("C2W.png",  "D2.png");
        MAPS.put("C3.png",   "D3.png");
        MAPS.put("C4.png",   "D4.png");
        MAPS.put("C5W.png",  "D5.png");
        MAPS.put("C6W.png",  "D6.png");
        MAPS.put("C7W.png",  "D7.png");
        MAPS.put("C8.png",   "D6.png");
        MAPS.put("C9W.png",  "D9.png");
        MAPS.put("C10W.png", "D10.png");
        MAPS.put("C11W.png", "D11.png");
        MAPS.put("C12W.png", "D11.png");
        MAPS.put("C13.png",  "D13.png");
        MAPS.put("C14.png",  "D14.png");
        MAPS.put("C14W.png", "D14.png");
        MAPS.put("C15.png",  "D15.png");
        MAPS.put("C16W.png", "D16.png");
        MAPS.put("C17W.png", "D17.png");
        MAPS.put("C18W.png", "D18.png");
        MAPS.put("C19W.png", "D19.png");
        MAPS.put("C20W.png", "D20.png");
        MAPS.put("C21.png",  "D21.png");
        MAPS.put("C22W.png", "D22.png");
        MAPS.put("C23W.png", "D21.png");
        MAPS.put("C24W.png", "D24.png");
        MAPS.put("C25W.png", "D25.png");
        MAPS.put("C26W.png", "D18.png");
        MAPS.put("C27W.png", "D15.png");
        MAPS.put("C28W.png", "D25.png");
        MAPS.put("C29W.png", "D16.png");
    }

    /** Creates new form FormSettings */
    public FormSettings() {
        initComponents();
        
        chkMultithreading.setSelected(Global.multithreading);
        
        Camera camera = FormMain.INSTANCE.getCamera();
        int distance = (int) camera.getDistance();
        sldDistance.setValue((int) camera.getDistance());
        
        sldDetalization.setValue((int) (Global.detalization * 10000));
        
        chkGravity.setSelected(camera.isEnableGravity());
        
        btnSkyColor.setBackground(new Color(Global.skyColor));
        
        chkFog.setSelected(Global.fogEnabled);
        btnFogColor.setBackground(new Color(Global.fogColor));
        
        sldFogEnd  .setMinimum(0);
        sldFogStart.setMinimum(0);
        sldFogEnd  .setMaximum(distance);
        sldFogStart.setMaximum(distance);
        sldFogEnd  .setValue((int) Global.fogEnd);
        sldFogStart.setValue((int) Global.fogStart);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkMultithreading = new javax.swing.JCheckBox();
        sldDistance = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        sldDetalization = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chkGravity = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        btnSkyColor = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmbMap = new javax.swing.JComboBox<>();
        chkFog = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        btnFogColor = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        sldFogStart = new javax.swing.JSlider();
        jLabel11 = new javax.swing.JLabel();
        sldFogEnd = new javax.swing.JSlider();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Settings");
        setAlwaysOnTop(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        chkMultithreading.setSelected(true);
        chkMultithreading.setText("Multithreading");
        chkMultithreading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMultithreadingActionPerformed(evt);
            }
        });

        sldDistance.setMaximum(4096);
        sldDistance.setMinimum(128);
        sldDistance.setValue(4096);
        sldDistance.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldDistanceStateChanged(evt);
            }
        });

        jLabel1.setText("Distance");

        sldDetalization.setMaximum(1500);
        sldDetalization.setMinimum(1);
        sldDetalization.setPaintTicks(true);
        sldDetalization.setValue(200);
        sldDetalization.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldDetalizationStateChanged(evt);
            }
        });

        jLabel2.setText("Detalization");

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel3.setText("Keys");

        jLabel4.setText("W/S or Up/Down - Move Forward/Backward");

        jLabel5.setText("Left/Right - Turn Left/Right");

        jLabel6.setText("A/D - Strafe Left/Right");

        chkGravity.setText("Gravity");
        chkGravity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkGravityActionPerformed(evt);
            }
        });

        jLabel7.setText("Sky Color");

        btnSkyColor.setBackground(new java.awt.Color(226, 13, 13));
        btnSkyColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkyColorActionPerformed(evt);
            }
        });

        jLabel8.setText("Map");

        cmbMap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C1W.png", "C2W.png", "C3.png", "C4.png", "C5W.png", "C6W.png", "C7W.png", "C8.png", "C9W.png", "C10W.png", "C11W.png", "C12W.png", "C13.png", "C14.png", "C14W.png", "C15.png", "C16W.png", "C17W.png", "C18W.png", "C19W.png", "C20W.png", "C21.png", "C22W.png", "C23W.png", "C24W.png", "C25W.png", "C26W.png", "C27W.png", "C28W.png", "C29W.png" }));
        cmbMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMapActionPerformed(evt);
            }
        });

        chkFog.setText("Fog");
        chkFog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFogActionPerformed(evt);
            }
        });

        jLabel9.setText("Fog Color");

        btnFogColor.setBackground(new java.awt.Color(226, 13, 13));
        btnFogColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFogColorActionPerformed(evt);
            }
        });

        jLabel10.setText("Fog Start");

        sldFogStart.setValue(10);
        sldFogStart.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldFogStartStateChanged(evt);
            }
        });

        jLabel11.setText("Fog End");

        sldFogEnd.setValue(100);
        sldFogEnd.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldFogEndStateChanged(evt);
            }
        });

        jLabel12.setText("Q/Z - Move Up/Down");

        jLabel13.setText("E/C - Look Up/Down");

        jLabel14.setText("M - MouseLook");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(cmbMap, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkFog)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addComponent(btnFogColor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sldFogEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sldFogStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(chkMultithreading, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(38, 38, 38)
                                    .addComponent(sldDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(chkGravity))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sldDetalization, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(26, 26, 26)
                                .addComponent(btnSkyColor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMultithreading)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addComponent(sldDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sldDetalization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(chkGravity))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(btnSkyColor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkFog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9))
                    .addComponent(btnFogColor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(sldFogStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(sldFogEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkMultithreadingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMultithreadingActionPerformed
        Global.multithreading = chkMultithreading.isSelected();
    }//GEN-LAST:event_chkMultithreadingActionPerformed

    private void sldDistanceStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldDistanceStateChanged
        Camera camera = FormMain.INSTANCE.getCamera();
        int distance = sldDistance.getValue();
        camera.setDistance(sldDistance.getValue());
        sldFogStart.setMaximum(distance);
        sldFogEnd.setMaximum(distance);
    }//GEN-LAST:event_sldDistanceStateChanged

    private void chkGravityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkGravityActionPerformed
        Camera camera = FormMain.INSTANCE.getCamera();
        camera.enableGravity(chkGravity.isSelected());
    }//GEN-LAST:event_chkGravityActionPerformed

    private void sldDetalizationStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldDetalizationStateChanged
        Global.detalization = sldDetalization.getValue() * 0.0001;
    }//GEN-LAST:event_sldDetalizationStateChanged

    private void btnSkyColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkyColorActionPerformed
        new DialogChooseColor(this, true, Global.skyColor).setVisible(true);
        Global.skyColor = DialogChooseColor.selectedColor;
        btnSkyColor.setBackground(new Color(Global.skyColor));
    }//GEN-LAST:event_btnSkyColorActionPerformed

    private void cmbMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMapActionPerformed
        String colorMap  = (String) cmbMap.getSelectedItem();
        String heightMap = MAPS.get(colorMap);
        
        FormMain.INSTANCE.getMap().load(colorMap, heightMap);
    }//GEN-LAST:event_cmbMapActionPerformed

    private void chkFogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFogActionPerformed
        Global.fogEnabled = chkFog.isSelected();
    }//GEN-LAST:event_chkFogActionPerformed

    private void btnFogColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFogColorActionPerformed
        new DialogChooseColor(this, true, Global.fogColor).setVisible(true);
        Global.fogColor = DialogChooseColor.selectedColor;
        btnFogColor.setBackground(new Color(Global.fogColor));
    }//GEN-LAST:event_btnFogColorActionPerformed

    private void sldFogStartStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldFogStartStateChanged
        int value = sldFogStart.getValue();
        Global.fogStart = value;
        if (sldFogEnd.getValue() < value) {
            sldFogEnd.setValue(value);
            Global.fogEnd = value;
        }
    }//GEN-LAST:event_sldFogStartStateChanged

    private void sldFogEndStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldFogEndStateChanged
        int value = sldFogEnd.getValue();
        if (value < sldFogStart.getValue()) {
            value = sldFogStart.getValue();
            sldFogEnd.setValue(value);
        }
        
        Global.fogEnd = value;
    }//GEN-LAST:event_sldFogEndStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFogColor;
    private javax.swing.JButton btnSkyColor;
    private javax.swing.JCheckBox chkFog;
    private javax.swing.JCheckBox chkGravity;
    private javax.swing.JCheckBox chkMultithreading;
    private javax.swing.JComboBox<String> cmbMap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSlider sldDetalization;
    private javax.swing.JSlider sldDistance;
    private javax.swing.JSlider sldFogEnd;
    private javax.swing.JSlider sldFogStart;
    // End of variables declaration//GEN-END:variables

}
